
version: '2.1'

services:
  web:
    container_name: drupal_web
    build:
      dockerfile: web.Dockerfile
      context: .
    ports:
      - "8085:80"
    volumes:
      # Anonymous volumes for composer-created directories
      - /var/www/drupal/.composer/cache
      - /var/www/drupal/vendor 
      - /var/www/drupal/web/core/
      - /var/www/drupal/web/modules/contrib/
      - /var/www/drupal/web/themes/contrib/
      - /var/www/drupal/web/profiles/contrib/
      # The volumes where our code lies
      - ./web:/var/www/drupal/web
      - ./config:/var/www/drupal/config
      # composer.json/lock for two-way binding.
      - ./composer.json:/var/www/drupal/composer.json
      - ./composer.lock:/var/www/drupal/composer.lock
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
  
  db:
    container_name: drupal_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /var/lib/mysql