
version: '2'

services:
  web:
    container_name: drupal_web
    build:
      dockerfile: web.Dockerfile
      context: .
    ports:
      - "8085:80"
    volumes:
      - ./web:/var/www/drupal/web
  
  db:
    container_name: drupal_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /var/lib/mysql